### ISSUE TITLE
not able to pick up internet facing interface 

### ISSUE THREAD

**Issue by patkszen** [xdavidhu/mitmAP#147]
there's seem to be an issue when I input interface connected to the internet, doesn't matter which interface I use. I've installed all needed dependencies while running the script for the first time 

[?] Install/Update dependencies? Y/n: 'n'   
[?] Please enter the name of your wireless interface (for the AP): 'test'
[?] Please enter the name of your internet connected interface: wlan0 
Traceback (most recent call last):
  File "mitmAP.py", line 70, in <module>
    net_iface = input("[?] Please enter the name of your internet connected interface: ")
  File "<string>", line 1, in <module>
NameError: name 'wlan0' is not defined

when I try 'wlan0'

[?] Please enter the name of your internet connected interface: 'wlan0'
[I] Backing up NetworkManager.cfg...
[I] Editing NetworkManager.cfg...
Traceback (most recent call last):
  File "mitmAP.py", line 76, in <module>
    write_file("/etc/NetworkManager/NetworkManager.conf", network_manager_cfg )
  File "mitmAP.py", line 36, in write_file
    _run_cmd_write((sudo, tee, path), s)
  File "mitmAP.py", line 29, in _run_cmd_write
    stdout=subprocess.DEVNULL,
AttributeError: 'module' object has no attribute 'DEVNULL'

Also it seems there's a problem with user input need to use single quotes, see the below:
[?] Install/Update dependencies? Y/n: 'n'

**Comment by patkszen** [comment]
I've run once again with python 3 and all works fine
