### ISSUE TITLE
Confirming with 'y' is not defined when installing dependencies

### ISSUE THREAD

**Issue by ghost** [xdavidhu/mitmAP#157]
Thats a quick start and quick end lol, do I miss something?

Install/Update dependencies? Y/n: Y
Traceback (most recent call last):
  File "mitmAP.py", line 48, in <module>
    update = input("[?] Install/Update dependencies? Y/n: ")
  File "<string>", line 1, in <module>
NameError: name 'Y' is not defined

**Comment by l4jos** [comment]
This happens running the script using python instead of python3. My wrong.
